document.addEventListener('DOMContentLoaded', function() {
    const searchInput = document.getElementById('searchInput');
    const suggestionsDiv = document.getElementById('suggestions');

    // Przykładowe dane do autouzupełniania
    const suggestions = [
        '300', 
		'7 Krasnoludków: Historia prawdziwa', 
		'7 Krasnoludków: Historia jeszcze prawdziwsza: Las to za mało', 
		'Adamczyk: Legendarny stream z Bimbeshem', 
		'Akademia Policyjna', 
		'Arcane', 
		'Arcydzieło, czyli dekalog producenta filmowego', 
		'Asterix Gall', 
		'Asterix i Kleopatra', 
		'12 Prac Asterixa',
		'Asterix kontra Cezar', 
		'Asterix w Brytanii', 
		'Wielka Bitwa Asterixa', 
		'Asterix podbija Amerykę', 
		'Asterix i Obelix kontra Cezar', 
		'Asterix i Obelix Misja Kleopatra', 
		'Asterix i Wikingowie', 
		'Asterix na olimpiadzie', 
		'Asterix i Obelix: Imperium Smoka', 
		'Auta', 
		'Auta 2', 
		'Auta 3', 
		'Avatar: Legenda Aanga Księga I - Woda', 
		'Avatar: Legenda Aanga Księga II - Ziemia', 
		'Avatar: Legenda Aanga Księga III - Ogień', 
		'Avatar: Legenda Korry Księga I - Powietrze', 
		'Avatar: Legenda Korry Księga II - Duchy', 
		'Avatar: Legenda Korry Księga III - Zmiana', 
		'Avatar: Legenda Korry Księga IV - Równowaga', 
		'Barbie', 
		'Bionicle Maska Światła', 
		'Bionicle 2 Legendy Metru Nui', 
		'Bionicle 3 W sieci mroku', 
		'Bionicle Narodziny Legendy', 
		'Bleach: Arc 01 Agent Shinigami', 
		'Bleach: Arc 02 Soul Society: Wejście Donosiciela', 
		'Bleach: Arc 03 Soul Society: Ratunek', 
		'Bleach: Arc 06 Arrancar: Przybycie', 
		'Bleach: Arc 07 Arrancar: Wejście do Hueco Mundo', 
		'Bleach: Arc 08 Arrancar: Zacięty Bój', 
		'Bleach: Arc 17 Tysiącletnia krwawa Wojna', 
		'Bleach: Arc 18 Tysiącletnia krwawa Wojna - Separacja', 
		'Bobobo-Bo Bo-Bobo', 
		'Bocchi The Rock!', 
		'Breaking Bad Sezon 1', 
		'Breaking Bad Sezon 2', 
		'Breaking Bad Sezon 3', 
		'Breaking Bad Sezon 4', 
		'Breaking Bad Sezon 5', 
		'Burn the Witch', 
		'But Manitou', 
		'Buty nieboszczyka', 
		'Chainsaw Man', 
		'Chomik', 
		'Chorobliwie Ostrożny Bohater', 
		'Czarnobyl', 
		'Czerwony Kapturek Prawdziwa Historia', 
		'Dan Brown Kod Da Vinci', 
		'Dan Brown Anioły i Demony', 
		'Dan Brown Inferno', 
		'Deadpool', 
		'Deadpool 2', 
		'Deadpool i Wolverine', 
		'Demonzz1 Stream dekady', 
		'Demonzz1 Urodzinowa noc odkupienia', 
		'Detroit Metal City', 
		'Dorohedoro', 
		'Drive', 
		'Dumbbell Nan Kilo Moteru', 
		'Dzieciaki', 
		'Dziewczyna Influencera', 
		'Epoka Lodowcowa', 
		'Epoka Lodowcowa 2 Odwilż', 
		'Epoka Lodowcowa 3 Era dinozaurów', 
		'Epoka Lodowcowa 4 Wędrówka kontynentów', 
		'Epoka Lodowcowa 5 Mocne uderzenie', 
		'Epoka Lodowcowa Przygody dzikiego Bucka', 
		'Eromanga Sensei', 
		'Fallout', 
		'Fantasy Bishoujo Juniku Ojisan to', 
		'Fate/Zero', 
		'Fate Carnival Phantasm', 
		'Ferrari', 
		'Ferrari: Wyścig po nieśmiertelność', 
		'Film o Pszczołach', 
		'FilthyFrank The Cake Trilogy', 
		'FlexAir', 
		'Fullmetal Alchemist Brotherhood', 
		'Gdzie jest Nemo', 
		'Gladiator', 
		'Goblin Slayer', 
		'Goblin Slayer Goblin`s Crown', 
		'Goblin Slayer II', 
		'Godzilla i Kong: Nowe Imperium', 
		'Godzilla: Minus One', 
		'Gothic Prawdziwa Historia', 
		'Gothic Prawdziwa Historia Kontynuacja Alternatywna', 
		'Gothic Prawdziwa Historia Remake', 
		'Grand Blue', 
		'Gran Turismo', 
		'Gucio GTA RP Seria 1', 
		'Gucio GTA RP Seria 2', 
		'Gwiezdne Wojny I Mroczne widmo', 
		'Gwiezdne Wojny II Atak Klonów', 
		'Gwiezdne Wojny III Zemsta Sithów', 
		'Gwiezdne Wojny IV Nowa nadzieja', 
		'Gwiezdne Wojny V Imperium Kontraatakuje', 
		'Gwiezdne Wojny VI Powrót Jedi', 
		'Gwiezdne Wojny Historie Łotr 1', 
		'Gwiezdne Wojny Historie Han Solo', 
		'Hazbin Hotel', 
		'Hellboy', 
		'Hellboy II Złota Armia', 
		'Iron Man', 
		'Iron Man 2', 
		'Iron Man 3', 
		'Isekai Ojisan', 
		'Ishuzoku Reviewers', 
		'Jack Strong', 
		'Jigokuraku Hell`s Paradise', 
		'Job Czyli ostatnia szara komórka', 
		'Jojo`s Bizarre Adventure', 
		'Joker', 
		'Jujutsu Kaisen Zero', 
		'Kac Vegas', 
		'Kaguya-Sama Love is War', 
		'Kaguya-Sama Love is War 2', 
		'Kaguya-Sama Love is War Ultra Romantic', 
		'Kapitan Bomba', 
		'Kapitan Bomba Laserowy Gniew Dzidy', 
		'Kapitan Bomba Kutapokalipsa', 
		'Kapitan Bomba Zemsta Faraona', 
		'Kaskader', 
		'Kiniro Mosaic', 
		'Klopsiki i inne zjawiska pogodowe', 
		'Kono Subarashii Sekai ni Shukufuku wo!', 
		'Kono Subarashii Sekai ni Shukufuku wo! 2', 
		'Kono Subarashii Sekai ni Shukufuku wo! Kurenai Densetsu', 
		'Kono Subarashii Sekai ni Shukufuku wo! 3', 
		'Kono Subarashii Sekai ni Bakuen wo!', 
		'Koralina i tajemnicze drzwi', 
		'Kosmiczny Mecz', 
		'Kot w Butach: Ostatnie Życzenie', 
		'Kryptonim: Klan Na Drzewie Sezon 1', 
		'Kryptonim: Klan Na Drzewie Sezon 2', 
		'Kryptonim: Klan Na Drzewie Sezon 3', 
		'Kryptonim: Klan Na Drzewie Sezon 4', 
		'Kryptonim: Klan Na Drzewie Sezon 5', 
		'Kryptonim: Klan Na Drzewie Sezon 6', 
		'Księga Ocalenia', 
		'Kung Fu Panda', 
		'Kung Fu Panda 2', 
		'Kung Fu Panda 3', 
		'Kung Fu Panda 4', 
		'Kung Fu Szał', 
		'Lamborghini: Człowiek, który stworzył legendę', 
		'Le Mans `66 Ferrari vs Ford', 
		'Liga niezwykłych dżentelmenów', 
		'Lilo i Stich', 
		'Lilo i Stich 2 Mały feler Stitcha', 
		'Made in Abyss', 
		'Made in Abyss Dawn of The Deep Soul', 
		'Made in Abyss 2 The Golden City of the Scorching Sun', 
		'Magnaci i Czarodzieje', 
		'Mahou Shoujo ni Akogarete', 
		'Martin Tajemniczy', 
		'Martin Tajemniczy 2', 
		'Martin Tajemniczy 3', 
		'Megamocny', 
		'Miasto Gniewu', 
		'Mój sąsiad Totoro', 
		'Mushoku Tensei', 
		'Mushoku Tensei Part 2', 
		'Mushoku Tensei 2', 
		'Mushoku Tensei 2 Part 2', 
		'Na Fali', 
		'Nekopara OVA', 
		'Nekopara OVA Koneko no Hi no Yakusoku', 
		'Nekopara', 
		'Nie zadzieraj z Fryzjerem', 
		'No Game No Life', 
		'No Game No Life Zero', 
		'Odlot', 
		'O-Jik Geu-Dea-Man', 
		'One Piece', 
		'One Punch Man', 
		'One Punch Man 2', 
		'Oppenheimer', 
		'Orcs!', 
		'Ostatni Skaut', 
		'Palm Springs', 
		'Panty & Stocking with Garterbelt', 
		'Piorun', 
		'Piraci z Karaibów Klątwa Czarnej Perły', 
		'Piraci z Karaibów Skrzynia Umarlaka', 
		'Piraci z Karaibów Na krańcu świata', 
		'Piraci z Karaibów Na nieznanych wodach', 
		'Piraci z Karaibów Zemsta Salazara', 
		'Planeta 51', 
		'Planeta Skarbów', 
		'Podwodna Bestia', 
		'Potwory i spółka', 
		'Potwory i spółka Uniwersytet Potworny', 
		'Poznaj moich Spartan', 
		'Prison School', 
		'Pulp Fiction', 
		'Ralph Demolka', 
		'Ralph Demolka w internecie', 
		'Rango', 
		'ReZero: Kara Hajimeru Isekai Seikatsu', 
		'ReZero: Kara Hajimeru Isekai Seikatsu Wspomnienie śniegu', 
		'ReZero: Kara Hajimeru Isekai Seikatsu Więzi skute lodem', 
		'ReZero: Kara Hajimeru Isekai Seikatsu 2', 
		'ReZero: Kara Hajimeru Isekai Seikatsu 3', 
		'Roboty', 
		'RRRrrrr!!!', 
		'Samuraj Jack Sezon 1', 
		'Samuraj Jack Sezon 2', 
		'Samuraj Jack Sezon 3', 
		'Samuraj Jack Sezon 4', 
		'Sewayaki Kitsune no Senko-san', 
		'Shikonoko Nokonoko Koshitantan', 
		'Shoujo Ramune', 
		'Shrek', 
		'Shrek 2', 
		'Shrek Trzeci', 
		'Shrek Forever After', 
		'Solo Leveling', 
		'Sousou no Frieren', 
		'Spider-man', 
		'Spider-man 2', 
		'Spider-man 3', 
		'Spider-man Uniwersum', 
		'Spider-man Poprzez Multiwersum', 
		'Straszny Dom', 
		'Superhero Movie', 
		'Super Mario Bros', 
		'Super Mario Bros Film', 
		'Ściema po polsku', 
		'Taksówkarz', 
		'Taxi', 
		'TESTOVIRON Wszystkie filmy Chronologicznie', 
		'The Boys Sezon 1', 
		'The Boys Sezon 2', 
		'The Boys Sezon 3', 
		'The Boys Sezon 4', 
		'Toradora!', 
		'Turysta', 
		'Tytus Romek i A`Tomek wśród złodzei marzeń', 
		'Ucieczka z Nowego Yorku', 
		'Vinland Saga Sezon 1', 
		'Vinland Saga Sezon 2', 
		'Wakfu: Goultard Barbarzyńca', 
		'Dofus Skarby Keruba', 
		'Dofus: Księga 1 - Julith', 
		'Wakfu', 
		'Wakfu: Zegarmistrz Noximilien', 
		'Wakfu: Legenda o Ogreście', 
		'Wakfu Sezon 2', 
		'Wakfu: W poszukiwaniu Sześciu Dofusów Eliatropów', 
		'Wakfu Sezon 3', 
		'Wakfu: Oropo Bitwa o Eliacube', 
		'Wakfu Sezon 4', 
		'Wall-E', 
		'Wallace i Gromit Klątwa Królika', 
		'Who killed Captain Alex', 
		'Władca Pierścieni Drużyna Pierścienia', 
		'Władca Pierścieni Dwie Wieże', 
		'Władca Pierścieni Powrót Króla', 
		'Wodogrzmoty małe Sezon 1', 
		'Wodogrzmoty małe Sezon 2', 
		'Wodogrzmoty małe Odcinki specjalne', 
		'Wściekłe Pięści Węża', 
		'Wyspa Tajemnic', 
		'Wyścig', 
		'Xiaolin Pojedynek Mistrzów Sezon 1', 
		'Xiaolin Pojedynek Mistrzów Sezon 2', 
		'Xiaolin Pojedynek Mistrzów Sezon 3', 
		'Zabijaka', 
		'Zwierzogród', 
    ];

    searchInput.addEventListener('input', function() {
        const query = searchInput.value.toLowerCase();
        suggestionsDiv.innerHTML = '';  // Czyszczenie wcześniejszych wyników

        if (query) {
            // Filtrowanie sugestii na podstawie wpisanego zapytania
            const filteredSuggestions = suggestions.filter(suggestion =>
                suggestion.toLowerCase().includes(query)
            );

            // Wyświetlanie sugestii
            filteredSuggestions.forEach(function(suggestion) {
                const suggestionItem = document.createElement('div');
                suggestionItem.classList.add('suggestion-item');
                suggestionItem.textContent = suggestion;
                suggestionsDiv.appendChild(suggestionItem);

                // Kliknięcie na sugestię wypełnia pole tekstowe
                suggestionItem.addEventListener('click', function() {
                    searchInput.value = suggestion;
                    suggestionsDiv.innerHTML = '';  // Usunięcie sugestii po wyborze
                });
            });
        }
    });

    // Opcjonalnie: kliknięcie poza listą ukrywa sugestie
    document.addEventListener('click', function(event) {
        if (!event.target.closest('.polewyszukiwania')) {
            suggestionsDiv.innerHTML = '';  // Ukrycie listy po kliknięciu poza
        }
    });
});