function autocomplete(inp, arr) {
  /*the autocomplete function takes two arguments,
  the text field element and an array of possible autocompleted values:*/
  var currentFocus;
  /*execute a function when someone writes in the text field:*/
  inp.addEventListener("input", function(e) {
      var a, b, i, val = this.value;
      /*close any already open lists of autocompleted values*/
      closeAllLists();
      if (!val) { return false;}
      currentFocus = -1;
      /*create a DIV element that will contain the items (values):*/
      a = document.createElement("DIV");
      a.setAttribute("id", this.id + "autocomplete-list");
      a.setAttribute("class", "autocomplete-items");
      /*append the DIV element as a child of the autocomplete container:*/
      this.parentNode.appendChild(a);
      /*for each item in the array...*/
      for (i = 0; i < arr.length; i++) {
        /*check if the item starts with the same letters as the text field value:*/
        if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
          /*create a DIV element for each matching element:*/
          b = document.createElement("DIV");
          /*make the matching letters bold:*/
          b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
          b.innerHTML += arr[i].substr(val.length);
          /*insert a input field that will hold the current array item's value:*/
          b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
          /*execute a function when someone clicks on the item value (DIV element):*/
          b.addEventListener("click", function(e) {
              /*insert the value for the autocomplete text field:*/
              inp.value = this.getElementsByTagName("input")[0].value;
              /*close the list of autocompleted values,
              (or any other open lists of autocompleted values:*/
              closeAllLists();
          });
          a.appendChild(b);
        }
      }
  });
  /*execute a function presses a key on the keyboard:*/
  inp.addEventListener("keydown", function(e) {
      var x = document.getElementById(this.id + "autocomplete-list");
      if (x) x = x.getElementsByTagName("div");
      if (e.keyCode == 40) {
        /*If the arrow DOWN key is pressed,
        increase the currentFocus variable:*/
        currentFocus++;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 38) { //up
        /*If the arrow UP key is pressed,
        decrease the currentFocus variable:*/
        currentFocus--;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 13) {
        /*If the ENTER key is pressed, prevent the form from being submitted,*/
        e.preventDefault();
        if (currentFocus > -1) {
          /*and simulate a click on the "active" item:*/
          if (x) x[currentFocus].click();
        }
      }
  });
  function addActive(x) {
    /*a function to classify an item as "active":*/
    if (!x) return false;
    /*start by removing the "active" class on all items:*/
    removeActive(x);
    if (currentFocus >= x.length) currentFocus = 0;
    if (currentFocus < 0) currentFocus = (x.length - 1);
    /*add class "autocomplete-active":*/
    x[currentFocus].classList.add("autocomplete-active");
  }
  function removeActive(x) {
    /*a function to remove the "active" class from all autocomplete items:*/
    for (var i = 0; i < x.length; i++) {
      x[i].classList.remove("autocomplete-active");
    }
  }
  function closeAllLists(elmnt) {
    /*close all autocomplete lists in the document,
    except the one passed as an argument:*/
    var x = document.getElementsByClassName("autocomplete-items");
    for (var i = 0; i < x.length; i++) {
      if (elmnt != x[i] && elmnt != inp) {
        x[i].parentNode.removeChild(x[i]);
      }
    }
  }
  /*execute a function when someone clicks in the document:*/
  document.addEventListener("click", function (e) {
      closeAllLists(e.target);
  });
}

/*An array containing all the country names in the world:*/
var filmy = [
		'7 Krasnoludków: Historia prawdziwa (2004)',
		'7 Krasnoludków: Historia jeszcze prawdziwsza: Las to za mało (2006)', 
		'9 (2009)',
		'13 Posterunek (1997-1998)',
		'13 Posterunek 2 (2000)',
		'21.37 (2025)',
		'127 godzin (2010)',
        '300 (2006)',
		'1670 (2023)',
		'2012 (2009)',
		'500000000 years button (2022)',
		'Ach, ten Andy! (2001-2007)',
		'Adamczyk: Legendarny stream z Bimbeshem (2022)', 
		'Adamczyk: Ostra patologia w Krakowie (2024)',
		'Akademia Policyjna (1984)', 
		'Anora (2024)',
		'Apocalypto (2006)',
		'Arcane (2021)', 
		'Arcane Sezon 2 (2024)',
		'Arcydzieło, czyli dekalog producenta filmowego (2023)', 
		'Asterix Gall (1967)', 
		'Asterix i Kleopatra (1968)', 
		'12 Prac Asterixa (1976)',
		'Asterix kontra Cezar (1985)', 
		'Asterix w Brytanii (1986)', 
		'Wielka Bitwa Asterixa (1989)', 
		'Asterix podbija Amerykę (1994)', 
		'Asterix i Obelix kontra Cezar (1999)', 
		'Asterix i Obelix Misja Kleopatra (2002)', 
		'Asterix i Wikingowie (2006)', 
		'Asterix na olimpiadzie (2008)', 
		'Asterix i Obelix: Imperium Smoka (2023)', 
		'Attack on Titan (2013)',
		'Attack on Titan Sezon 2 (2017)',
		'Attack on Titan Sezon 3 (2018-2019)',
		'Attack on Titan Sezon 4 (2020-2022)',
		'Atomówki (1998-2004)',
		'Auta (2006)', 
		'Auta 2 (2011)', 
		'Auta 3 (2017)', 
		'Avatar: Legenda Aanga Księga I - Woda (2005)', 
		'Avatar: Legenda Aanga Księga II - Ziemia (2006)', 
		'Avatar: Legenda Aanga Księga III - Ogień (2007-2008)', 
		'Avatar: Legenda Korry Księga I - Powietrze (2012)', 
		'Avatar: Legenda Korry Księga II - Duchy (2012)', 
		'Avatar: Legenda Korry Księga III - Zmiana (2014)', 
		'Avatar: Legenda Korry Księga IV - Równowaga (2014)', 
		'Barbie (2023)', 
		'Ben 10 (2005-2008)',
		'Berserk The Golden Age arc I: The egg of the king (2012)',
		'Berserk The Golden Age arc II: The battle for Doldrey (2012)',
		'Bibliotekarz: Tajemnica Włóczni (2004)',
		'Bibliotekarz II: Tajemnice kopalni króla Salomona (2006)',
		'Bibliotekarz III: Klątwa kielicha Judasza (2008)',
		'Bionicle Maska Światła (2003)', 
		'Bionicle 2 Legendy Metru Nui (2004)', 
		'Bionicle 3 W sieci mroku (2005)', 
		'Bionicle Narodziny Legendy (2009)', 
		'Bleach: Arc 01 Agent Shinigami (2004-2005)', 
		'Bleach: Arc 02 Soul Society: Wejście Donosiciela (2005)', 
		'Bleach: Arc 03 Soul Society: Ratunek (2005-2006)', 
		'Bleach: Arc 06 Arrancar: Przybycie (2007)', 
		'Bleach: Arc 07 Arrancar: Wejście do Hueco Mundo (2007)', 
		'Bleach: Arc 08 Arrancar: Zacięty Bój (2007)', 
		'Bleach: Arc 10 Arrancar kontra Shinigami (2008-2009)',
		'Bleach: Arc 11 Przeszłość (2009)',
		'Bleach: Arc 12 Decydująca bitwa o Karakurę (2009)',
		'Bleach: Arc 14 Arrancar: Upadek (2010-2011)',
		'Bleach: Arc 16 Zaginiony agent Shinigami (2011-2012)',
		'Bleach: Arc 17 Tysiącletnia krwawa wojna (2022)', 
		'Bleach: Arc 18 Tysiącletnia krwawa wojna - Separacja (2023)', 
		'Bleach: Arc 19 Tysiącletnia krwawa wojna - Konflikt (2024)',
		'Bliźniaki Cramp (2003-2005)',
		'Bobobo-Bo Bo-Bobo (2003-2005)', 
		'Bocchi The Rock! (2022)', 
		'BOFURI: I don`t want to get hurt, so I`ll max out my defense (2020)', 
		'BOFURI: I don`t want to get hurt, so I`ll max out my defense 2 (2023)',
		'Breaking Bad Sezon 1 (2008)', 
		'Breaking Bad Sezon 2 (2009)', 
		'Breaking Bad Sezon 3 (2010)', 
		'Breaking Bad Sezon 4 (2011)', 
		'Breaking Bad Sezon 5 (2012-2013)', 
		'Bronzowe Myśli (2014-2019)',
		'Bronzowe Myśli: Tymczasem (2015-2018)',
		'Bronzowe Taktyki (2015-2016)',
		'Bruce Lee - Wściekłe Pięści (1972)',
		'Bruce Lee - Wejście smoka (1973)',
		'Brutalista (2024)',
		'Burn the Witch (2020)', 
		'But Manitou (2001)', 
		'Buty nieboszczyka (2004)', 
		'Był sobie kot (2024)',
		'Chainsaw Man (2022)', 
		'Chłopaki z baraków Sezon 1 (2001)', 
		'Chłopaki z baraków Sezon 2 (2002)', 
		'Chłopaki z baraków Sezon 3 (2003)', 
		'Chłopaki z baraków Sezon 4 (2004)', 
		'Chłopaki z baraków Sezon 5 (2005)', 
		'Chłopaki z baraków Sezon 6 (2006)', 
		'Chłopaki z baraków Sezon 7 (2007)', 
		'Chojrak tchórzliwy pies (1999-2002)',
		'Chomik (2001)', 
		'Chorobliwie Ostrożny Bohater (2019)', 
		'Chowder (2007-2010)',
		'Crash: Niebezpieczne pożądanie (1996)',
		'Czarnobyl (2019)', 
		'Czerwony Kapturek Prawdziwa Historia (2005)', 
		'Czerwony Kapturek 2 Pogromca Zła (2011)',
		'Człowiek demolka (1993)',
		'Dan Brown Kod Da Vinci (2006)', 
		'Dan Brown Anioły i Demony (2009)', 
		'Dan Brown Inferno (2016)', 
		'Dawno temu w trawie (1998)',
		'Deadpool (2016)', 
		'Deadpool 2 (2018)', 
		'Deadpool i Wolverine (2024)', 
		'Demonzz1 Stream dekady (2024)', 
		'Demonzz1 Urodzinowa noc odkupienia (2024)', 
		'Detroit Metal City (2008)', 
		'Deuraegon bol: Ssawora Son O-gong, igyeora Son O-gong (1990)',
		'Dinokrokodyl kontra Supergator (2010)',
		'Dom dla zmyślonych przyjacioł Pani Foster (2004-2009)',
		'Dorohedoro (2020)', 
		'Dragon Ball (1986-1989)',
		'Drive (2011)', 
		'Dumbbell Nan Kilo Moteru (2019)', 
		'Dzieciaki (1995)', 
		'Dzień świra (2002)',
		'Dziewczyna Influencera (2024)', 
		'Dziki Robot (2024)',
		'Ed Edd i Eddy Sezon 1',
		'Ed Edd i Eddy Sezon 2',
		'Ed Edd i Eddy Sezon 3',
		'Ed Edd i Eddy Sezon 4',
		'Ed Edd i Eddy Sezon 5',
		'Ed Edd i Eddy Odcinki specjalne',
		'Epoka Lodowcowa', 
		'Epoka Lodowcowa 2 Odwilż', 
		'Epoka Lodowcowa 3 Era dinozaurów', 
		'Epoka Lodowcowa 4 Wędrówka kontynentów', 
		'Epoka Lodowcowa 5 Mocne uderzenie', 
		'Epoka Lodowcowa Przygody dzikiego Bucka', 
		'Eromanga Sensei', 
		'Fachowiec (2025)',
		'Fallout', 
		'Fantasy Bishoujo Juniku Ojisan to', 
		'Fate/Stay Night (2006)',
		'Fate/Zero (2011-2012)',
		'Fate: Carnival Phantasm (2011)',
		'Fate/Stay Night: Unlimited Blade Works (2014-2015)',
		'Fate/Apocrypha (2017)',
		'Ferrari', 
		'Ferrari: Wyścig po nieśmiertelność', 
		'Film o Pszczołach', 
		'FilthyFrank The Cake Trilogy', 
		'Fineasz i Ferb (2007-2015)',
		'FlexAir', 
		'Flow',
		'Foodfight!', 
		'Fullmetal Alchemist Brotherhood', 
		'Futurama (1999-2024)',
		'Garfield (2004)',
		'Gdzie jest Nemo (2003)', 
		'Gladiator', 
		'Gladiator II',
		'Goblin Slayer', 
		'Goblin Slayer Goblin`s Crown', 
		'Goblin Slayer II', 
		'Godzilla i Kong: Nowe Imperium', 
		'Godzilla: Minus One', 
		'Godziny szczytu',
		'Godziny szczytu 2',
		'Godziny szczytu 3',
		'Gothic Prawdziwa Historia', 
		'Gothic Prawdziwa Historia Kontynuacja Alternatywna', 
		'Gothic Prawdziwa Historia Remake', 
		'Gra o Tron Sezon 1 (2011)',
		'Gra o Tron Sezon 2 (2012)',
		'Gra o Tron Sezon 3 (2013)',
		'Gra o Tron Sezon 4 (2014)',
		'Gra o Tron Sezon 5 (2015)',
		'Gra o Tron Sezon 6 (2016)',
		'Gra o Tron Sezon 7 (2017)',
		'Gra o Tron Sezon 8 (2019)',
		'Grand Blue', 
		'Gran Turismo', 
		'Gucio GTA RP Seria 1', 
		'Gucio GTA RP Seria 2', 
		'Gwiezdne Wojny I Mroczne widmo (1999)', 
		'Gwiezdne Wojny II Atak Klonów (2002)', 
		'Gwiezdne Wojny III Zemsta Sithów (2005)', 
		'Gwiezdne Wojny IV Nowa nadzieja (1977)', 
		'Gwiezdne Wojny V Imperium Kontraatakuje (1980)', 
		'Gwiezdne Wojny VI Powrót Jedi (1983)',
		'Gwiezdne Wojny VII Przebudzenie mocy (2015)',
		'Gwiezdne Wojny VIII Ostatni Jedi (2017)',
		'Gwiezdne Wojny IX Skywalker odrodzenie (2019)',
		'Gwiezdne Wojny Wojny klonów miniserial 2D (2003)',
		'Gwiezdne Wojny Parszywa Zgraja Sezon 1 (2021)',
		'Gwiezdne Wojny Parszywa Zgraja Sezon 2 (2023)',
		'Gwiezdne Wojny Parszywa Zgraja Sezon 3 (2024)',
		'Gwiezdne Wojny Historie Han Solo (2018)', 
		'Gwiezdne Wojny Obi-Wan Kenobi (2022)',
		'Gwiezdne Wojny Rebelianci Sezon 1 (2014-2015)',
		'Gwiezdne Wojny Rebelianci Sezon 2 (2015-2016)',
		'Gwiezdne Wojny Rebelianci Sezon 3 (2016-2017)',
		'Gwiezdne Wojny Rebelianci Sezon 4 (2017-2018)',
		'Gwiezdne Wojny Andor (2022)',
		'Gwiezdne Wojny Andor Sezon 2 (2025)',
		'Gwiezdne Wojny Historie Łotr 1 (2016)', 
		'Gwiezdne Wojny The Mandalorian Sezon 1 (2019)',
		'Gwiezdne Wojny The Mandalorian Sezon 2 (2020)',
		'Gwiezdne Wojny The Mandalorian Sezon 3 (2023)',
		'Gwiezdne Wojny Ahsoka (2023)',
		'Gwiezdne Wojny Wizje (2021)',
		'Gwiezdne Wojny Wizje 2 (2023)',
		'Harcerz Lazlo (2005-2008)',
		'Harry Potter i Kamień Filozoficzny',
		'Harry Potter i Komnata Tajemnic',
		'Harry Potter i więzień Azkabanu',
		'Harry Potter i Czara Ognia',
		'Harry Potter i Zakon Feniksa',
		'Harry Potter i Książę Półkrwi',
		'Harry Potter i Insygnia Śmierci Część 1',
		'Harry Potter i Insygnia Śmierci Część 2',
		'Fantastyczne Zwierzęta i jak je znaleźć',
		'Fantastyczne Zwierzęta: Zbrodnie Grindelwalda',
		'Fantastyczne Zwierzęta: Tajemnice Dumbledore`a',
		'Hazbin Hotel', 
		'Hellboy', 
		'Hellboy II Złota Armia', 
		'Hej Arnold! (2005-2008)',
		'Higurashi no Naku Koro ni (2006)',
		'Higurashi no Naku Koro ni Kai (2007)',
		'Higurashi no Naku Koro ni Gou (2020-2021)',
		'Higurashi no Naku Koro ni Sotsu (2021)',
		'Huntik: Łowcy Tajemnic Sezon 1',
		'Huntik: Łowcy Tajemnic Sezon 2',
		'Igrzyska na kacu (2014)',
		'Iluzja', 
		'Iluzja 2', 
		'Indiana Jones i poszukiwacze zaginionej Arki (1981)',
		'Indiana Jones i Świątynia Zagłady (1984)',
		'Indiana Jones i Ostatnia Krucjata (1989)',
		'Indiana Jones i Królestwo kryształowej czaszki (2008)',
		'Iniemamocni (2004)',
		'Iniemamocni 2 (2018)',
		'Inspektor Gadget (1983-1986)',
		'Interstellar (2014)',
		'Invincible (2021)',
		'Invincible Sezon 2 (2024)',
		'Invincible Sezon 3 (2025)',
		'Iron Man', 
		'Iron Man 2', 
		'Iron Man 3', 
		'Isekai Ojisan', 
		'Ishuzoku Reviewers', 
		'Jack Strong', 
		'Jackie Chan - Pijany Mistrz', 
		'Jackie Chan - Zbroja Boga (1986)',
		'Jackie Chan - Zbroja Boga II (1991)',
		'Jackie Chan - Pierwsze uderzenie', 
		'Jackie Chan - Przyjemniaczek', 
		'Jackie Chan - Zgadnij kim jestem (1998)',
		'Jackie Chan - Kowboj z Szanghaju', 
		'Jackie Chan - Rycerze z Szanghaju',
		'Jackie Chan - Agent z przypadku',  
		'Jackie Chan - Chiński Zodiak (2012)',
		'Jakub Patecki. Misja: Mount Everest (2024)',
		'Jakub Patecki. Projekt Antarktyda (2025)',
		'James Bond 23: Skyfall',
		'James Bond 24: Spectre',
		'James Bond 25: Nie czas umierać',
		'Jigokuraku Hell`s Paradise', 
		'Job Czyli ostatnia szara komórka', 
		'Johnny Bravo Sezon 1',
		'Johnny Bravo Sezon 2',
		'Johnny Bravo Sezon 3',
		'Johnny Bravo Sezon 4',
		'Jojo`s Bizarre Adventure', 
		'Joker', 
		'Joker: Folie à Deux',
		'Jujutsu Kaisen',
		'Jujutsu Kaisen Zero', 
		'Jujutsu Kaisen 2',
		'Jumanji (1995)',
		'Kac Vegas (2009)',
		'Kac Vegas w Bangkoku (2011)',
		'Kac Vegas III (2013)',
		'Kaguya-Sama Love is War', 
		'Kaguya-Sama Love is War 2', 
		'Kaguya-Sama Love is War Ultra Romantic', 
		'Kamdesh. Afgańskie Piekło (2019)',
		'Kapitan Bomba', 
		'Kapitan Bomba Laserowy Gniew Dzidy', 
		'Kapitan Bomba Kutapokalipsa', 
		'Kapitan Bomba Zemsta Faraona', 
		'Kapitan Orgazmo (1997)',
		'Karate Kid',
		'Kaskader', 
		'Kevin sam w domu', 
		'Kevin sam w Nowym Jorku', 
		'Kiniro Mosaic', 
		'Klopsiki i inne zjawiska pogodowe', 
		'Kono Subarashii Sekai ni Shukufuku wo!', 
		'Kono Subarashii Sekai ni Shukufuku wo! 2', 
		'Kono Subarashii Sekai ni Shukufuku wo! Kurenai Densetsu', 
		'Kono Subarashii Sekai ni Shukufuku wo! 3', 
		'Kono Subarashii Sekai ni Bakuen wo!', 
		'Koralina i tajemnicze drzwi', 
		'Kosmiczny Mecz', 
		'Kot w Butach: Ostatnie Życzenie', 
		'Kotopies (1998-2001)',
		'K-popowe łowczynie demonów (2025)',
		'Krowy na wypasie (2006)',
		'Król Lew: Mufasa',
		'Królestwo Niebieskie',
		'Kryptonim: Klan Na Drzewie Sezon 1', 
		'Kryptonim: Klan Na Drzewie Sezon 2', 
		'Kryptonim: Klan Na Drzewie Sezon 3', 
		'Kryptonim: Klan Na Drzewie Sezon 4', 
		'Kryptonim: Klan Na Drzewie Sezon 5', 
		'Kryptonim: Klan Na Drzewie Sezon 6', 
		'Krzysiu, gdzie jesteś? (2018)',
		'Książę Egiptu (1998)',
		'Księga Ocalenia (2010)', 
		'Kung Fu Panda', 
		'Kung Fu Panda 2', 
		'Kung Fu Panda 3', 
		'Kung Fu Panda 4', 
		'Kung Fu Szał', 
		'Kung Pow - Wejście Wybrańca (2002)',
		'Kurczak mały',
		'Laboratorium Dextera (1996-2003)',
		'Lamborghini: Człowiek, który stworzył legendę', 
		'Legendy Sowiego Królestwa: Strażnicy Ga`Hoole', 
		'Le Mans `66 Ford vs Ferrari', 
		'Liga niezwykłych dżentelmenów', 
		'Lilo i Stich', 
		'Lilo i Stich 2 Mały feler Stitcha', 
		'Luźny gość', 
		'Madagaskar (2005)',
		'Madagaskar 2 (2008)',
		'Madagaskar 3 (2012)',
		'Made in Abyss', 
		'Made in Abyss Dawn of The Deep Soul', 
		'Made in Abyss 2 The Golden City of the Scorching Sun', 
		'Magnaci i Czarodzieje', 
		'Mahou Shoujo ni Akogarete', 
		'Martin Tajemniczy', 
		'Martin Tajemniczy 2', 
		'Martin Tajemniczy 3', 
		'Megamocny', 
		'Miasto Gniewu', 
		'Mickey 17 (2025)',
		'Miłość, Śmierć i Roboty (2019)',
		'Miłość, Śmierć i Roboty Sezon 2 (2021)',
		'Miłość, Śmierć i Roboty Sezon 3 (2022)',
		'Miłość, Śmierć i Roboty Sezon 4 (2025)',
		'Minecraft Film (2025)',
		'Mordercza Choinka (2022)',
		'Mój brat niedźwiedź',
		'Mój partner z sali gimnastycznej jest małpą (2005-2008)',
		'Mushoku Tensei', 
		'Mushoku Tensei Part 2', 
		'Mushoku Tensei 2', 
		'Mushoku Tensei 2 Part 2', 
		'Na Fali', 
		'Nekopara OVA', 
		'Nekopara OVA Koneko no Hi no Yakusoku', 
		'Nekopara', 
		'Niania (2005-2009)',
		'Niekończąca się opowieść II: Następny rozdział (1990)',
		'Nie zadzieraj z Fryzjerem', 
		'No Game No Life', 
		'No Game No Life Zero', 
		'Nowe szaty króla',
		'Nowe szaty króla 2 Kronk - Nowe wcielenie',
		'Obszar Badawczy Szkolna XVII',
		'Odlot', 
		'Ojciec Chrzestny (1972)',
		'Ojciec Chrzestny II (1974)',
		'Ojciec Chrzestny III (1990)',
		'O-Jik Geu-Dea-Man', 
		'One Piece', 
		'One Punch Man', 
		'One Punch Man 2', 
		'Operacja Świt',
		'Opowiadania Muminków',
		'Pamiętniki Tatusia Muminka',
		'Oppenheimer', 
		'Orcs!', 
		'Ostatni Skaut', 
		'Palm Springs', 
		'Panty & Stocking with Garterbelt', 
		'Paul (2011)',
		'Piorun', 
		'Piraci z Karaibów Klątwa Czarnej Perły', 
		'Piraci z Karaibów Skrzynia Umarlaka', 
		'Piraci z Karaibów Na krańcu świata', 
		'Piraci z Karaibów Na nieznanych wodach', 
		'Piraci z Karaibów Zemsta Salazara', 
		'Planeta 51', 
		'Planeta Skarbów', 
		'Pocahontas',
		'Podwodna Bestia', 
		'Pokemon Indigo League (1997-1998)',
		'Potwory i spółka', 
		'Potwory i spółka Uniwersytet Potworny', 
		'Poznaj moich Spartan', 
		'Prison School', 
		'Psy (1992)',
		'Psy 2. Ostatnia krew (1994)',
		'Pulp Fiction', 
		'Putin (2025)',
		'Ralph Demolka', 
		'Ralph Demolka w internecie', 
		'Rango', 
		'Redo of Healer',
		'Re:Zero Kara Hajimeru Isekai Seikatsu', 
		'Re:Zero Kara Hajimeru Isekai Seikatsu Wspomnienie śniegu (2018)', 
		'Re:Zero Kara Hajimeru Isekai Seikatsu Więzi skute lodem', 
		'Re:Zero Kara Hajimeru Isekai Seikatsu Sezon 2', 
		'Re:Zero Kara Hajimeru Isekai Seikatsu Sezon 3', 
		'Rio (2011)',
		'Roboty', 
		'Rybki z Ferajny',
		'RRRrrrr!!!', 
		'Samuraj Jack Sezon 1', 
		'Samuraj Jack Sezon 2', 
		'Samuraj Jack Sezon 3', 
		'Samuraj Jack Sezon 4', 
		'Sasquatch Sunset (2024)',
		'Sausage Party (2016)',
		'Se7en (1995)',
		'Sewayaki Kitsune no Senko-san', 
		'Sexy-myjnia w bikini (2015)',
		'Sezon na misia', 
		'Shikanoko Nokonoko Koshitantan', 
		'Shoujo Ramune (2016-2018)', 
		'Shrek', 
		'Shrek 2', 
		'Shrek Trzeci', 
		'Shrek Forever After', 
		'Skazani na Shawshank (1994)',
		'Solo Leveling', 
		'Solo Leveling 2: Arise from the Shadow',
		'Sonic Szybki jak błyskawica',
		'Sonic Szybki jak błyskawica 2',
		'Sonic Szybki jak błyskawica 3',
		'Sonic X',
		'Sousou no Frieren', 
		'South Park (1997-2023)',
		'South Park - Bigger, Longer and Uncut (1999)',
		'Spider-man', 
		'Spider-man 2', 
		'Spider-man 3', 
		'Spider-man Uniwersum', 
		'Spider-man Poprzez Multiwersum', 
		'Stowarzyszenie Umarłych Poetów (1989)',
		'Stalker',
		'Straszny Dom', 
		'Stuber (2019)',
		'Studio Ghibli: Mój sąsiad Totoro',
		'Studio Ghibli: Spirited Away - W krainie Bogów',
		'Studio Ghibli: Ruchomy zamek Hauru',
		'Superhero Movie', 
		'Super Mario Bros', 
		'Super Mario Bros Film', 
		'Szczurwiel',
		'Szklana pułapka (1988)',
		'Szklana pułapka 2 (1990)',
		'Szklana pułapka 3 (1995)',
		'Ściema po polsku', 
		'Śmierć Stalina (2017)',
		'Świat według Kiepskich',
		'Świat według Ludwiczka Sezon 1',
		'Świat według Ludwiczka Sezon 2',
		'Świat według Ludwiczka Sezon 3',
		'Taksówkarz', 
		'Tarzan',
		'Taxi', 
		'TESTOVIRON Wszystkie filmy Chronologicznie', 
		'The Boys Sezon 1', 
		'The Boys Sezon 2', 
		'The Boys Sezon 3', 
		'The Boys Sezon 4', 
		'The Last of Us (2023)',
		'Toradora!',
		'Touhou Gensou Mangekyou - The Memories of Phantasm (2011-2023)',
		'Toy Story (1995)',
		'Toy Story 2 (1999)',
		'Toy Story 3 (2010)',
		'Toy Story 4 (2019)',
		'Transporter',
		'Transporter 2',
		'Transporter 3',
		'Troll (2022)',
		'Turysta', 
		'Tytus Romek i A`Tomek wśród złodzei marzeń', 
		'Ucieczka z Nowego Yorku', 
		'u Pana Boga za piecem (1998)',
		'u Pana Boga w ogródku (2007)',
		'Vaiana Skarb oceanu (2016)',
		'Vaiana 2 (2024)',
		'Vinland Saga Sezon 1', 
		'Vinland Saga Sezon 2', 
		'W 80 dni dookoła świata',
		'Wajutsushi',
		'Wakfu: Goultard Barbarzyńca', 
		'Dofus Skarby Keruba', 
		'Dofus: Księga 1 - Julith', 
		'Wakfu', 
		'Wakfu: Zegarmistrz Noximilien', 
		'Wakfu: Legenda o Ogreście', 
		'Wakfu Sezon 2', 
		'Wakfu: W poszukiwaniu Sześciu Dofusów Eliatropów', 
		'Wakfu Sezon 3', 
		'Wakfu: Oropo Bitwa o Eliacube', 
		'Wakfu Sezon 4', 
		'Wall-E', 
		'Wallace i Gromit Klątwa Królika', 
		'Warfare (2025)',
		'Who killed Captain Alex', 
		'Wielki Stach (2007)',
		'Władca Pierścieni Drużyna Pierścienia', 
		'Władca Pierścieni Dwie Wieże', 
		'Władca Pierścieni Powrót Króla', 
		'Włoska Robota',
		'Wodogrzmoty małe Sezon 1', 
		'Wodogrzmoty małe Sezon 2', 
		'Wodogrzmoty małe Odcinki specjalne', 
		'Wściekłe Pięści Węża', 
		'Wyspa Tajemnic', 
		'Wyspa Totalnej Porażki',
		'Wyścig', 
		'Xiaolin Pojedynek Mistrzów Sezon 1', 
		'Xiaolin Pojedynek Mistrzów Sezon 2', 
		'Xiaolin Pojedynek Mistrzów Sezon 3', 
		'Yosuga no Sora',
		'Zabijaka', 
		'Zakazane królestwo (2008)',
		'Zoolander',
		'Zwierzogród', 
		'tag:Akcja',
		'tag:Dokumentalny',
		'tag:Dramat',
		'tag:Erotyczny',
		'tag:Fantasy',
		'tag:Horror',
		'tag:Historyczny',
		'tag:Komedia',
		'tag:Kryminał',
		'tag:Obyczajowy',
		'tag:Przygodowy',
		'tag:Psychologiczny',
		'tag:Romans',
		'tag:Sci-Fi',
		'tag:Stream',
		'tag:Thriller',
		'tag:Wojenny',
		'typ:Anime',
		'typ:Dokument',
		'typ:Film',
		'typ:Serial',
		'typ:Stream',
		'+3',
		'+7',
		'+12',
		'+16',
		'+18',
    ];

/*initiate the autocomplete function on the "myInput" element, and pass along the countries array as possible autocomplete values:*/
autocomplete(document.getElementById("myInput"), filmy);
